Repository kubernetes-sigs/reference-docs, pull requests merged in 2018-09, with the labels that each got.

#55 Fix links in the API reference generator
  gen-apidocs/generators/api/definition.go
  gen-apidocs/generators/html.go
Labels: cncf-cla: yes, size/XS

#57 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: cncf-cla: yes, lgtm, size/L

#60 Add static files for kubectl 1.12 docs
  gen-kubectldocs/generators/v1_12/static_includes/_app_management.md
  gen-kubectldocs/generators/v1_12/static_includes/_getting_started.md
  gen-kubectldocs/generators/v1_12/static_includes/_working_with_apps.md
  gen-kubectldocs/generators/v1_12/toc.yaml
Labels: cncf-cla: yes, lgtm, size/M
