Repository kubernetes-sigs/reference-docs, pull requests merged in 2019-12, with the labels that each got.

#95 Update bootstrap to 4.3.1 to match k8s/website
  gen-apidocs/generators/static/bootstrap.min.css
Labels: approved, cncf-cla: yes, lgtm, size/S

#98 Fix CSS file for API reference
  gen-apidocs/generators/static/bootstrap.min.css
Labels: approved, cncf-cla: yes, size/S

#102 Drop 'brodocs' backend for API reference generation
  gen-apidocs/generators/Dockerfile
  gen-apidocs/generators/md.go
  gen-apidocs/generators/static_includes/_cluster.md
  gen-apidocs/generators/static_includes/_config.md
  gen-apidocs/generators/static_includes/_definitions.md
  gen-apidocs/generators/static_includes/_meta.md
  gen-apidocs/generators/static_includes/_oldversions.md
  gen-apidocs/generators/static_includes/_overview.md
  gen-apidocs/generators/static_includes/_servicediscovery.md
  gen-apidocs/generators/static_includes/_workloads.md
  gen-apidocs/generators/util.go
  gen-apidocs/generators/writer.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
