Repository kubernetes-sigs/reference-docs, pull requests merged in 2019-09, with the labels that each got.

#85 Fix the error from 'go get -u'
  doc.go
Labels: cncf-cla: yes, size/XS

#86 cleanup commands
  .travis.yml
  gen-compdocs/generators/gen_kube_docs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#87 Includes missing introductions
  gen-apidocs/generators/html.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#89 Fix the JS version referenced by API docs
  gen-apidocs/generators/html.go
Labels: cncf-cla: yes, size/XS

#90 Add comments to html.go generateHTML
  gen-apidocs/generators/html.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#91 Fix version and add label selector for replicaset example
  gen-apidocs/generators/examples/replicaset/replicaset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#92 Update owners and security contacts
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS
