Repository kubernetes-sigs/reference-docs, pull requests merged in 2019-03, with the labels that each got.

#67 Update apps versions used in examples
  gen-apidocs/generators/examples/deployment/create.yaml
  gen-apidocs/generators/examples/deployment/deployment.yaml
  gen-apidocs/generators/examples/deployment/patch.yaml
  gen-apidocs/generators/examples/deployment/read.yaml
  gen-apidocs/generators/examples/deployment/replace.yaml
  gen-apidocs/generators/examples/deployment/watch.yaml
  gen-apidocs/generators/static_includes/_workloads.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#72 Fix group comparison
  gen-apidocs/generators/api/api.go
  gen-apidocs/generators/api/definition.go
  gen-apidocs/generators/api/types.go
  gen-apidocs/generators/config.yaml
Labels: cncf-cla: yes, size/L

#73 Fix group comparison for v1.14 (master)
  gen-apidocs/generators/api/api.go
  gen-apidocs/generators/api/definition.go
  gen-apidocs/generators/api/types.go
  gen-apidocs/generators/config.yaml
Labels: cncf-cla: yes, size/L

#74 Stop checking out upstream repo when doing CI checking
  .travis.yml
Labels: cncf-cla: yes, size/S

#66 Add tool-reference templating
  gen-compdocs/generators/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#75 Drop support to brodocs way of doc generator
  Dockerfile
  Makefile
Labels: cncf-cla: yes, size/M
