Repository kubernetes-sigs/reference-docs, pull requests merged in 2020-01, with the labels that each got.

#110 Fix HTML display for API reference
  gen-apidocs/generators/html.go
  gen-apidocs/static/css/stylesheet.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#114 Add selector field to Deployment v1 apps example
  gen-apidocs/config/examples/deployment/create.yaml
  gen-apidocs/config/examples/deployment/deployment.yaml
  gen-apidocs/config/examples/deployment/replace.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#116 Add selector field to DaemonSet v1 apps example
  gen-apidocs/config/examples/daemonset/create.yaml
  gen-apidocs/config/examples/daemonset/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#115 remove an extra `]`
  gen-apidocs/config/sections/_config.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#120 correct updateapispec tgt
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#125 Backport changes to release-1.16
  gen-apidocs/generators/examples/daemonset/create.yaml
  gen-apidocs/generators/examples/daemonset/daemonset.yaml
  gen-apidocs/generators/examples/deployment/create.yaml
  gen-apidocs/generators/examples/deployment/deployment.yaml
  gen-apidocs/generators/examples/deployment/replace.yaml
  gen-apidocs/generators/static/stylesheet.css
  gen-apidocs/generators/static_includes/_config.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#128 Make sure API responses are sorted
  gen-apidocs/generators/html.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#129 modify setting of spec version
  Makefile
  gen-apidocs/generators/api/config.go
  gen-apidocs/generators/api/open_api.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#130 clean up script and makefile
  Makefile
  set_version_dirs.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
