Repository kubernetes-sigs/reference-docs, pull requests merged in 2020-07, with the labels that each got.

#161 Migrate shared API assets to website repo
  Makefile
  gen-apidocs/generators/html.go
  gen-apidocs/static/css/bootstrap.min.css
  gen-apidocs/static/css/font-awesome.min.css
  gen-apidocs/static/css/stylesheet.css
  gen-apidocs/static/fonts/FontAwesome.otf
  gen-apidocs/static/fonts/fontawesome-webfont.eot
  gen-apidocs/static/fonts/fontawesome-webfont.svg
  gen-apidocs/static/fonts/fontawesome-webfont.ttf
  gen-apidocs/static/fonts/fontawesome-webfont.woff
  gen-apidocs/static/fonts/fontawesome-webfont.woff2
  gen-apidocs/static/js/jquery.scrollTo.min.js
  gen-apidocs/static/js/scroll.js
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#162 Tweak owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#165 Allowing generating API reference for RC versions
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#166 Update resource config for release 1.19
  gen-apidocs/config/v1_19/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#168 Fix warning about CSR approval
  gen-apidocs/generators/api/operation.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
