Repository kubernetes-sigs/reference-docs, pull requests merged in 2020-03, with the labels that each got.

#137 Tweak the page content style
  gen-apidocs/static/css/stylesheet.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#133 create dirs for 1.18 release
  gen-apidocs/config/v1_18/config.yaml
  gen-kubectldocs/generators/v1_18/static_includes/_app_management.md
  gen-kubectldocs/generators/v1_18/static_includes/_getting_started.md
  gen-kubectldocs/generators/v1_18/static_includes/_working_with_apps.md
  gen-kubectldocs/generators/v1_18/toc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#140 Update to use latest brodocs and fixed unescaped < and > in generated docs
  Makefile
  README.md
  gen-kubectldocs/generators/gen.go
  runbrodocs.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#142 Fix usage and hyperlinks in kubectl reference
  gen-kubectldocs/generators/gen.go
  gen-kubectldocs/generators/templates.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#145 Update nginx to modern versions
  gen-apidocs/config/examples/container/container.yaml
  gen-apidocs/config/examples/deployment/create.yaml
  gen-apidocs/config/examples/deployment/deployment.yaml
  gen-apidocs/config/examples/deployment/list.yaml
  gen-apidocs/config/examples/deployment/patch.yaml
  gen-apidocs/config/examples/deployment/read.yaml
  gen-apidocs/config/examples/deployment/replace.yaml
  gen-apidocs/config/examples/deployment/watch.yaml
  gen-apidocs/config/examples/replicaset/replicaset.yaml
  gen-apidocs/config/examples/replicationcontroller/replicationcontroller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
