Repository kubernetes-sigs/reference-docs, pull requests merged in 2020-12, with the labels that each got.

#181 Fix API generation for v1.20 (rc.0)
  gen-apidocs/config/v1_20/config.yaml
  gen-apidocs/generators/api/config.go
  gen-apidocs/generators/api/definition.go
  gen-apidocs/generators/api/open_api.go
  gen-apidocs/generators/api/operation.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#185 add mkdir for catalina docker build
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#184 Allow customization of the full names for groups
  gen-apidocs/config/v1_20/config.yaml
  gen-apidocs/generators/api/config.go
  gen-apidocs/generators/api/definition.go
  gen-apidocs/generators/api/open_api.go
  gen-apidocs/generators/api/types.go
  gen-apidocs/generators/api/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#183 Expose group mapping into config file.
  Makefile
  gen-apidocs/config/v1_20/config.yaml
  gen-apidocs/generators/api/config.go
  gen-apidocs/generators/api/definition.go
  gen-apidocs/generators/api/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M
