Repository kubernetes-sigs/reference-docs, pull requests merged in 2021-04, with the labels that each got.

#210 Add outputs from genref tool
  genref/config.yaml
  genref/markdown/members.tpl
  genref/markdown/pkg.tpl
  genref/markdown/type.tpl
  genref/output/html/apiserver-audit.v1.html
  genref/output/html/apiserver-config.v1.html
  genref/output/html/apiserver-config.v1beta1.html
  genref/output/html/apiserver-encryption.v1.html
  genref/output/html/apiserver-resourcequota.v1.html
  genref/output/html/apiserver-webhookadmission.v1.html
  genref/output/html/client-authentication.v1beta1.html
  genref/output/html/cloud-provider-config.v1alpha1.html
  genref/output/html/cloud-provider-service.v1alpha1.html
  genref/output/html/kube-controller-manager-config.v1alpha1.html
  genref/output/html/kube-proxy-config.v1alpha1.html
  genref/output/html/kube-scheduler-config.v1beta1.html
  genref/output/html/kube-scheduler-policy-config.v1.html
  genref/output/html/kubeadm-config.v1beta1.html
  genref/output/html/kubeadm-config.v1beta2.html
  genref/output/html/kubelet-config.v1beta1.html
  genref/output/html/metrics.v1beta1.html
  genref/output/md/apiserver-audit.v1.md
  genref/output/md/apiserver-config.v1.md
  genref/output/md/apiserver-config.v1beta1.md
  genref/output/md/apiserver-encryption.v1.md
  genref/output/md/apiserver-resourcequota.v1.md
  genref/output/md/apiserver-webhookadmission.v1.md
  genref/output/md/client-authentication.v1beta1.md
  genref/output/md/cloud-provider-config.v1alpha1.md
  genref/output/md/cloud-provider-service.v1alpha1.md
  genref/output/md/kube-controller-manager-config.v1alpha1.md
  genref/output/md/kube-proxy-config.v1alpha1.md
  genref/output/md/kube-scheduler-config.v1beta1.md
  genref/output/md/kube-scheduler-policy-config.v1.md
  genref/output/md/kubeadm-config.v1beta1.md
  genref/output/md/kubeadm-config.v1beta2.md
  genref/output/md/kubelet-config.v1beta1.md
  genref/output/md/metrics.v1beta1.md
  genref/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#220 Use code tag instead of samp for config API types
  genref/config.yaml
  genref/markdown/members.tpl
  genref/markdown/pkg.tpl
  genref/markdown/type.tpl
  genref/types.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/M

#222 Fix reference generation for kube-proxy config
  genref/config.yaml
  genref/output/html/kube-proxy-config.v1alpha1.html
  genref/output/md/kube-proxy-config.v1alpha1.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#225 Update reference generator for 1.21
  genref/Makefile
  genref/go.mod
  genref/go.sum
  genref/main.go
  genref/types.go
  genref/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#223 Update go modules for component reference 1.21
  .travis.yml
  gen-compdocs/go.mod
  gen-compdocs/go.sum
Labels: approved, cncf-cla: yes, size/L

#228 Tune Makefile and Travis config
  .travis.yml
  Makefile
  genref/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#229 Add auto_generated metadata and comment to discourage direct edition
  gen-resourcesdocs/templates/chapter-single-definition.tmpl
  gen-resourcesdocs/templates/chapter.tmpl
  gen-resourcesdocs/templates/part-index.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M
