Repository kubernetes-sigs/reference-docs, pull requests merged in 2021-08, with the labels that each got.

#249 Update go mod for component ref for 1.22
  gen-compdocs/go.mod
  gen-compdocs/go.sum
Labels: cncf-cla: yes, size/XL, lgtm, approved

#251 Update kubectl config for 1.22
  Makefile
  gen-kubectldocs/generators/v1_22/static_includes/_app_management.md
  gen-kubectldocs/generators/v1_22/static_includes/_getting_started.md
  gen-kubectldocs/generators/v1_22/static_includes/_working_with_apps.md
  gen-kubectldocs/generators/v1_22/toc.yaml
  gen-kubectldocs/go.mod
  gen-kubectldocs/go.sum
Labels: cncf-cla: yes, size/L, lgtm, approved

#252 updating co-chairs
  OWNERS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/XS, lgtm, approved
