Repository kubernetes-sigs/reference-docs, pull requests merged in 2021-01, with the labels that each got.

#186 resourcedocs: Add Anchors to inlined definitions
  gen-resourcesdocs/pkg/config/output.go
  gen-resourcesdocs/pkg/config/output_test.go
  gen-resourcesdocs/pkg/outputs/interface.go
  gen-resourcesdocs/pkg/outputs/kwebsite/chapter.go
  gen-resourcesdocs/pkg/outputs/kwebsite/files.go
  gen-resourcesdocs/pkg/outputs/kwebsite/section.go
  gen-resourcesdocs/templates/chapter-single-definition.tmpl
  gen-resourcesdocs/templates/chapter.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#190 update module name
  gen-resourcesdocs/cmd/cli/gvkeysmap.go
  gen-resourcesdocs/cmd/cli/helpers.go
  gen-resourcesdocs/cmd/cli/resourceslist.go
  gen-resourcesdocs/cmd/main.go
  gen-resourcesdocs/go.mod
  gen-resourcesdocs/go.sum
  gen-resourcesdocs/pkg/config/categories.go
  gen-resourcesdocs/pkg/config/chapter.go
  gen-resourcesdocs/pkg/config/output.go
  gen-resourcesdocs/pkg/config/output_test.go
  gen-resourcesdocs/pkg/config/toc.go
  gen-resourcesdocs/pkg/config/toc_test.go
  gen-resourcesdocs/pkg/kubernetes/apigroup_test.go
  gen-resourcesdocs/pkg/kubernetes/apiversion_test.go
  gen-resourcesdocs/pkg/kubernetes/resource_test.go
  gen-resourcesdocs/pkg/kubernetes/spec.go
  gen-resourcesdocs/pkg/kubernetes/spec_test.go
  gen-resourcesdocs/pkg/openapi/openapi_test.go
  gen-resourcesdocs/pkg/outputs/interface.go
  gen-resourcesdocs/pkg/outputs/kwebsite/chapter.go
  gen-resourcesdocs/pkg/outputs/kwebsite/kwebsite.go
  gen-resourcesdocs/pkg/outputs/kwebsite/part.go
  gen-resourcesdocs/pkg/outputs/kwebsite/section.go
  gen-resourcesdocs/templates/chapter-single-definition.tmpl
  gen-resourcesdocs/templates/chapter.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#197 revise gencomp and travis
  .travis.yml
  Makefile
  gen-compdocs/Makefile
  gen-compdocs/generators/gen_kube_docs.go
  gen-compdocs/go.mod
  gen-compdocs/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#196 API reference: Do not generate main index
  gen-resourcesdocs/pkg/config/output.go
  gen-resourcesdocs/pkg/config/toc.go
  gen-resourcesdocs/pkg/outputs/interface.go
  gen-resourcesdocs/pkg/outputs/kwebsite/files.go
  gen-resourcesdocs/pkg/outputs/kwebsite/kwebsite.go
  gen-resourcesdocs/templates/main-index.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#171 SIG Docs chair transition
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#194 add feloy as reviewer/approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#201 Add warnings in the generated files
  gen-compdocs/generators/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#204 Remove non alphanumeric characters from anchors
  gen-resourcesdocs/templates/chapter-single-definition.tmpl
  gen-resourcesdocs/templates/chapter.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#205 Fix defaulting in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
