Repository kubernetes-sigs/reference-docs, pull requests merged in 2021-07, with the labels that each got.

#238 Fix doc strings for kubeadm config
  genref/go.mod
  genref/go.sum
  genref/output/md/kubeadm-config.v1beta1.md
  genref/output/md/kubeadm-config.v1beta2.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#239 Kube scheduler v1beta2
  genref/config.yaml
  genref/go.mod
  genref/go.sum
  genref/output/md/kube-scheduler-config.v1beta2.md
  genref/output/md/kubeadm-config.v1beta2.md
  genref/output/md/kubeadm-config.v1beta3.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#242 Update mod version for genref
  genref/config.yaml
  genref/go.mod
  genref/go.sum
  genref/output/md/kubeadm-config.v1beta2.md
  genref/output/md/kubeadm-config.v1beta3.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#244 Re-enable v1alpha1 for apiserver APIs
  genref/config.yaml
  genref/output/md/apiserver-config.v1alpha1.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#248 use k8s-staging-images vs kubernetes-ci-images
  genref/output/html/kubeadm-config.v1beta1.html
  genref/output/html/kubeadm-config.v1beta2.html
Labels: approved, cncf-cla: yes, lgtm, size/XS
