Repository kubernetes-sigs/reference-docs, pull requests merged in 2022-05, with the labels that each got.

#273 Update go.mod for 1.24.0 component reference
  gen-compdocs/go.mod
  gen-compdocs/go.sum
Labels: cncf-cla: yes, size/L, lgtm, approved

#274 Update config API generator and generated files for 1.24
  genref/config.yaml
  genref/go.mod
  genref/go.sum
  genref/output/md/apiserver-audit.v1.md
  genref/output/md/kube-controller-manager-config.v1alpha1.md
  genref/output/md/kube-proxy-config.v1alpha1.md
  genref/output/md/kube-scheduler-config.v1beta2.md
  genref/output/md/kube-scheduler-config.v1beta3.md
  genref/output/md/kubeadm-config.v1beta3.md
  genref/output/md/kubelet-config.v1alpha1.md
  genref/output/md/kubelet-config.v1beta1.md
  genref/output/md/kubelet-credentialprovider.v1beta1.md
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#275 Update kubectl generator for 1.24
  gen-kubectldocs/generators/gen.go
  gen-kubectldocs/generators/v1_24/static_includes/_app_management.md
  gen-kubectldocs/generators/v1_24/static_includes/_getting_started.md
  gen-kubectldocs/generators/v1_24/static_includes/_working_with_apps.md
  gen-kubectldocs/generators/v1_24/toc.yaml
  gen-kubectldocs/go.mod
  gen-kubectldocs/go.sum
Labels: cncf-cla: yes, size/XL, lgtm, sig/cli, approved

#278 Update reference to kubeadm config
  genref/go.mod
  genref/go.sum
  genref/output/md/kubeadm-config.v1beta2.md
  genref/output/md/kubeadm-config.v1beta3.md
Labels: cncf-cla: yes, size/M, lgtm, approved
