Repository kubernetes-sigs/reference-docs, pull requests merged in 2022-09, with the labels that each got.

#296 update links
  CONTRIBUTING.md
  kubectl.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#298 broken link issue resolved
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#300 Update configuration YAML for API reference v1.25
  gen-apidocs/config/config.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#299 Update config for kubectl reference v1.25
  gen-kubectldocs/generators/v1_25/static_includes/_app_management.md
  gen-kubectldocs/generators/v1_25/static_includes/_getting_started.md
  gen-kubectldocs/generators/v1_25/static_includes/_working_with_apps.md
  gen-kubectldocs/generators/v1_25/toc.yaml
  gen-kubectldocs/go.mod
  gen-kubectldocs/go.sum
Labels: cncf-cla: yes, size/XL, lgtm, approved
