Repository kubernetes-sigs/reference-docs, pull requests merged in 2023-10, with the labels that each got.

#341 Fix package level template for config API reference
  genref/config.yaml
  genref/main.go
  genref/markdown/pkg.tpl
  genref/output/md/kubeconfig.v1.md
  genref/types.go
Labels: cncf-cla: yes, size/L, approved

#342 Update the generated config API files
  genref/output/md/apiserver-admission.v1.md
  genref/output/md/apiserver-audit.v1.md
  genref/output/md/apiserver-config.v1.md
  genref/output/md/apiserver-config.v1alpha1.md
  genref/output/md/apiserver-config.v1beta1.md
  genref/output/md/apiserver-encryption.v1.md
  genref/output/md/apiserver-eventratelimit.v1alpha1.md
  genref/output/md/apiserver-resourcequota.v1.md
  genref/output/md/apiserver-webhookadmission.v1.md
  genref/output/md/client-authentication.v1.md
  genref/output/md/client-authentication.v1beta1.md
  genref/output/md/cloud-provider-config.v1alpha1.md
  genref/output/md/cloud-provider-service.v1alpha1.md
  genref/output/md/custom-metrics.v1beta2.md
  genref/output/md/external-metrics.v1beta1.md
  genref/output/md/imagepolicy.v1alpha1.md
  genref/output/md/kube-controller-manager-config.v1alpha1.md
  genref/output/md/kube-proxy-config.v1alpha1.md
  genref/output/md/kube-scheduler-config.v1.md
  genref/output/md/kube-scheduler-config.v1beta3.md
  genref/output/md/kube-scheduler-extender.v1.md
  genref/output/md/kubeadm-config.v1beta3.md
  genref/output/md/kubeadm-config.v1beta4.md
  genref/output/md/kubelet-config.v1.md
  genref/output/md/kubelet-config.v1alpha1.md
  genref/output/md/kubelet-config.v1beta1.md
  genref/output/md/kubelet-credentialprovider.v1.md
  genref/output/md/kubelet-credentialprovider.v1alpha1.md
  genref/output/md/kubelet-credentialprovider.v1beta1.md
  genref/output/md/kubelet-stats.v1alpha1.md
  genref/output/md/metrics.v1beta1.md
Labels: cncf-cla: yes, size/XXL, approved

#343 [genref] Strip prefix in map types.
  genref/types.go
Labels: cncf-cla: yes, size/S, lgtm, approved
