Repository kubernetes-sigs/reference-docs, pull requests merged in 2023-12, with the labels that each got.

#348 Update configuration for component reference v1.29
  gen-compdocs/generators/doc.go
  gen-compdocs/go.mod
  gen-compdocs/go.sum
Labels: cncf-cla: yes, size/XL, lgtm, approved

#346 Update configuration for genref v1.29
  genref/config.yaml
  genref/go.mod
  genref/go.sum
  genref/output/md/apiserver-admission.v1.md
  genref/output/md/apiserver-audit.v1.md
  genref/output/md/apiserver-config.v1alpha1.md
  genref/output/md/apiserver-resourcequota.v1.md
  genref/output/md/client-authentication.v1.md
  genref/output/md/client-authentication.v1beta1.md
  genref/output/md/custom-metrics.v1beta2.md
  genref/output/md/external-metrics.v1beta1.md
  genref/output/md/imagepolicy.v1alpha1.md
  genref/output/md/kube-controller-manager-config.v1alpha1.md
  genref/output/md/kube-proxy-config.v1alpha1.md
  genref/output/md/kube-scheduler-config.v1.md
  genref/output/md/kube-scheduler-config.v1beta3.md
  genref/output/md/kubeadm-config.v1beta3.md
  genref/output/md/kubeadm-config.v1beta4.md
  genref/output/md/kubelet-config.v1beta1.md
  genref/output/md/kubelet-credentialprovider.v1.md
  genref/output/md/kubelet-credentialprovider.v1alpha1.md
  genref/output/md/kubelet-credentialprovider.v1beta1.md
  genref/output/md/kubelet-stats.v1alpha1.md
  genref/output/md/metrics.v1beta1.md
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#330 [gen-resourcesdocs] fix Go lint issues, improve error handling
  gen-resourcesdocs/cmd/cli/cli.go
  gen-resourcesdocs/cmd/cli/helpers.go
  gen-resourcesdocs/go.mod
  gen-resourcesdocs/go.sum
  gen-resourcesdocs/pkg/config/categories.go
  gen-resourcesdocs/pkg/config/output.go
  gen-resourcesdocs/pkg/config/output_test.go
  gen-resourcesdocs/pkg/config/toc.go
  gen-resourcesdocs/pkg/config/toc_test.go
  gen-resourcesdocs/pkg/kubernetes/actions.go
  gen-resourcesdocs/pkg/kubernetes/apiversion.go
  gen-resourcesdocs/pkg/kubernetes/apiversion_test.go
  gen-resourcesdocs/pkg/kubernetes/extensions_test.go
  gen-resourcesdocs/pkg/kubernetes/spec.go
  gen-resourcesdocs/pkg/kubernetes/spec_test.go
  gen-resourcesdocs/pkg/openapi/openapi_test.go
  gen-resourcesdocs/pkg/outputs/kwebsite/files.go
  gen-resourcesdocs/pkg/outputs/kwebsite/kwebsite.go
  gen-resourcesdocs/pkg/outputs/kwebsite/section.go
Labels: cncf-cla: yes, size/L, lgtm, approved
