Repository kubernetes-sigs/reference-docs, pull requests merged in 2023-09, with the labels that each got.

#329 [genref] fix Go lint issues, improve error handling
  genref/Makefile
  genref/go.mod
  genref/go.sum
  genref/kube_deps.go
  genref/main.go
  genref/types.go
Labels: cncf-cla: yes, size/L

#332 [gen-compdocs] fix Go lint issues, improve error handling
  gen-compdocs/Makefile
  gen-compdocs/comps/gen_kube_docs.go
  gen-compdocs/generators/doc.go
  gen-compdocs/generators/postprocessing.go
  gen-compdocs/main.go
  gen-compdocs/proxy/main.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#333 [gen-apidocs] fix Go lint issues, improve error handling, replace navdata generator with regular JSON encoder
  gen-apidocs/generators/api/config.go
  gen-apidocs/generators/api/definition.go
  gen-apidocs/generators/api/examples.go
  gen-apidocs/generators/api/open_api.go
  gen-apidocs/generators/api/operation.go
  gen-apidocs/generators/api/types.go
  gen-apidocs/generators/api/util.go
  gen-apidocs/generators/html.go
  gen-apidocs/generators/writer.go
  gen-apidocs/main.go
Labels: cncf-cla: yes, size/XL, lgtm, approved

#331 [gen-kubectldocs] fix Go lint issues, improve error handling
  gen-kubectldocs/generators/gen.go
  gen-kubectldocs/go.mod
  gen-kubectldocs/main.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#334 [gen-apidocs] remove standalone navdata, use DOM instead
  gen-apidocs/config/sections/_cluster.html
  gen-apidocs/config/sections/_config.html
  gen-apidocs/config/sections/_definitions.html
  gen-apidocs/config/sections/_meta.html
  gen-apidocs/config/sections/_oldversions.html
  gen-apidocs/config/sections/_overview.html
  gen-apidocs/config/sections/_servicediscovery.html
  gen-apidocs/config/sections/_workloads.html
  gen-apidocs/generators/api/config.go
  gen-apidocs/generators/html.go
  gen-apidocs/generators/writer.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#335 [gen-apidocs] Fix HTML lint errors
  gen-apidocs/config/sections/_oldversions.html
  gen-apidocs/config/sections/_overview.html
  gen-apidocs/generators/html.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#337 add button to toggle dark/light mode
  gen-apidocs/generators/html.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#336 [gen-apidocs] fix missing definitions
  gen-apidocs/generators/html.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#338 fine-tune apidocs markup for dark mode
  gen-apidocs/generators/html.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#339 Update pkg dependency for genref
  genref/go.mod
  genref/go.sum
Labels: cncf-cla: yes, size/XS, approved
