Repository kubernetes-sigs/reference-docs, pull requests merged in 2024-04, with the labels that each got.

#349 Improve reference generator for kubectl
  gen-compdocs/generators/doc.go
  gen-compdocs/go.mod
  gen-compdocs/go.sum
  gen-compdocs/main.go
Labels: cncf-cla: yes, size/M, sig/docs, approved

#356 API reference generator adaptation for v1.30
  gen-apidocs/config/v1_30/config.yaml
  gen-apidocs/config/v1_30/swagger.json
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#357 Component reference generator config for v1.30
  gen-compdocs/go.mod
  gen-compdocs/go.sum
Labels: cncf-cla: yes, size/L, lgtm, approved

#358 Update config and buffered data for configapi 1.30
  genref/config.yaml
  genref/go.mod
  genref/go.sum
  genref/output/md/apiserver-admission.v1.md
  genref/output/md/apiserver-audit.v1.md
  genref/output/md/apiserver-config.v1.md
  genref/output/md/apiserver-config.v1alpha1.md
  genref/output/md/apiserver-config.v1beta1.md
  genref/output/md/apiserver-encryption.v1.md
  genref/output/md/apiserver-resourcequota.v1.md
  genref/output/md/client-authentication.v1.md
  genref/output/md/client-authentication.v1beta1.md
  genref/output/md/custom-metrics.v1beta2.md
  genref/output/md/external-metrics.v1beta1.md
  genref/output/md/imagepolicy.v1alpha1.md
  genref/output/md/kube-controller-manager-config.v1alpha1.md
  genref/output/md/kube-scheduler-config.v1.md
  genref/output/md/kubeadm-config.v1beta3.md
  genref/output/md/kubeadm-config.v1beta4.md
  genref/output/md/kubelet-config.v1beta1.md
  genref/output/md/kubelet-stats.v1alpha1.md
  genref/output/md/metrics.v1beta1.md
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#359 Add SIG Docs co-chairs to reference-docs owners
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved
