Repository kubernetes-sigs/reference-docs, pull requests merged in 2024-08, with the labels that each got.

#370 Add gen-apidocs config for 1.31
  gen-apidocs/config/v1_31/config.yaml
  gen-apidocs/config/v1_31/swagger.json
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#373 update configuration for v1.31 config API generation
  genref/config.yaml
  genref/go.mod
  genref/go.sum
Labels: cncf-cla: yes, size/L, lgtm, approved

#371 Configuration update for API reference v1.31
  gen-apidocs/config/v1_31/config.yaml
  gen-apidocs/generators/api/definition.go
  gen-apidocs/generators/util.go
  gen-apidocs/go.mod
  gen-apidocs/go.sum
Labels: cncf-cla: yes, size/L, lgtm, approved

#372 Update reference generator for kube components v1.31
  gen-compdocs/comps/gen_kube_docs.go
  gen-compdocs/generators/postprocessing.go
  gen-compdocs/go.mod
  gen-compdocs/go.sum
Labels: cncf-cla: yes, size/XL, lgtm, approved

#369 Exclude excludedOperations in misc operations
  gen-apidocs/generators/api/config.go
  gen-apidocs/generators/writer.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#375 Look through AdditionalProperties for references
  gen-apidocs/generators/api/definition.go
  gen-apidocs/generators/api/util.go
Labels: cncf-cla: yes, size/M, lgtm, approved
