Repository kubernetes-sigs/reference-docs, pull requests merged in 2025-09, with the labels that each got.

#404 Fix `navData.js` not generated in `make copyapi` command
  gen-apidocs/generators/html.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#405 Improve error handling and file operations in writer.go
  gen-apidocs/generators/html.go
  gen-apidocs/generators/writer.go
  gen-apidocs/go.mod
  gen-apidocs/go.sum
Labels: cncf-cla: yes, size/L, lgtm, approved

#400 Update resource API generator for v1.34
  gen-resourcesdocs/Makefile
  gen-resourcesdocs/api/v1.34/swagger.json
  gen-resourcesdocs/config/v1.34/fields.yaml
  gen-resourcesdocs/config/v1.34/toc.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#402 Update config API generator for v1.34
  genref/config.yaml
  genref/go.mod
  genref/go.sum
  genref/output/md/apiserver-admission.v1.md
  genref/output/md/apiserver-audit.v1.md
  genref/output/md/apiserver-config.v1.md
  genref/output/md/apiserver-config.v1alpha1.md
  genref/output/md/apiserver-config.v1beta1.md
  genref/output/md/apiserver-resourcequota.v1.md
  genref/output/md/client-authentication.v1.md
  genref/output/md/client-authentication.v1beta1.md
  genref/output/md/custom-metrics.v1beta2.md
  genref/output/md/external-metrics.v1beta1.md
  genref/output/md/imagepolicy.v1alpha1.md
  genref/output/md/kube-scheduler-config.v1.md
  genref/output/md/kubeadm-config.v1beta3.md
  genref/output/md/kubeadm-config.v1beta4.md
  genref/output/md/kubeconfig.v1.md
  genref/output/md/kubelet-config.v1.md
  genref/output/md/kubelet-config.v1alpha1.md
  genref/output/md/kubelet-config.v1beta1.md
  genref/output/md/kubelet-stats.v1alpha1.md
  genref/output/md/metrics.v1beta1.md
Labels: cncf-cla: yes, size/XXL, lgtm, approved
